[Icon Theme]
Name=GoHarder
Comment=GoHarder icon theme
DisplayDepth=32
Inherits=breeze-dark,Adwaita,hicolor
Example=folder
FollowsColorScheme=true
DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

KDE-Extensions=.svg

# Directories
# Ordered by category and alphabetically

# Directories=actions/12,actions/16,actions/22,actions/32,actions/48,actions/64,animations/16,animations/22,applets/16,applets/22,applets/32,applets/48,applets/64,applets/128,applets/256,apps/16,apps/22,apps/32,apps/48,apps/64,categories/22,categories/32,devices/16,devices/22,devices/32,devices/64,emblems/8,emblems/16,emblems/22,emotes/22,mimetypes/16,mimetypes/22,mimetypes/32,mimetypes/64,places/16,places/22,places/32,places/48,places/64,places/96,preferences/22,preferences/32,status/16,status/22,status/32,status/64
# ScaledDirectories=actions/16@2x,actions/16@3x,actions/22@2x,actions/22@3x,actions/32@2x,actions/32@3x,animations/16@2x,animations/16@3x,apps/16@2x,apps/16@3x,apps/22@2x,apps/22@3x,devices/16@2x,devices/16@3x,devices/22@2x,devices/22@3x,emblems/16@2x,emblems/16@3x,emblems/22@2x,emblems/22@3x,emotes/22@2x,emotes/22@3x,mimetypes/16@2x,mimetypes/16@3x,mimetypes/22@2x,mimetypes/22@3x,places/16@2x,places/16@3x,places/22@2x,places/22@3x,status/16@2x,status/16@3x,status/22@2x,status/22@3x

Directories=actions/16,actions/22,actions/32,categories/22,categories/32,devices/22,emblems/8,emblems/16,emblems/22,mimetypes/16,mimetypes/22,mimetypes/32,mimetypes/64,places/16,places/22,places/32,places/48,places/64,places/96,preferences/22,status/16,status/22,status/32,status/64
ScaledDirectories=actions/16@2x,actions/16@3x,actions/22@2x,actions/22@3x,actions/32@2x,actions/32@3x,devices/22@2x,devices/22@3x,emblems/16@2x,emblems/16@3x,emblems/22@2x,emblems/22@3x,mimetypes/16@2x,mimetypes/16@3x,mimetypes/22@2x,mimetypes/22@3x,places/16@2x,places/16@3x,places/22@2x,places/22@3x

# Actions

# 12x12 - Fixed size - For Inkscape
# [actions/12]
# Size=12
# Context=Actions
# Type=Fixed

# 16x16 Sidebars And Smaller Toolbar Icons
[actions/16]
Context=Actions
Size=16
Type=Fixed

# 16x16@2x Sidebars And Smaller Toolbar Icons
[actions/16@2x]
Context=Actions
Scale=2
Size=16
Type=Fixed

# 16x16@3x Sidebars And Smaller Toolbar Icons
[actions/16@3x]
Context=Actions
Scale=3
Size=16
Type=Fixed

# 22x22 - Toolbar icons
[actions/22]
Context=Actions
Size=22
Type=Fixed

# 22x22@2x - Toolbar icons
[actions/22@2x]
Context=Actions
Scale=2
Size=22
Type=Fixed

# 22x22@3x - Toolbar icons
[actions/22@3x]
Context=Actions
Scale=3
Size=22
Type=Fixed

# 32x32 - Toolbar icons
[actions/32]
Context=Actions
MaxSize=256
MinSize=32
Size=32
Type=Scalable

# 32x32@2x - Toolbar icons
[actions/32@2x]
Context=Actions
MaxSize=256
MinSize=32
Scale=2
Size=32
Type=Scalable

# 32x32@3x - Toolbar icons
[actions/32@3x]
Context=Actions
MaxSize=256
MinSize=32
Scale=3
Size=32
Type=Scalable

# 48x48 - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [actions/48]
# Size=48
# Context=Actions
# Type=Scalable
# MinSize=48
# MaxSize=256

# 64x64 - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [actions/64]
# Size=64
# Context=Actions
# Type=Scalable
# MinSize=32
# MaxSize=256

# Animations
# Ordered by size

# 16x16 - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [animations/16]
# Size=16
# Context=Animations
# Type=Fixed

# 16x16@2x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [animations/16@2x]
# Size=16
# Scale=2
# Context=Animations
# Type=Fixed

# 16x16@3x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [animations/16@3x]
# Size=16
# Scale=3
# Context=Animations
# Type=Fixed

# 22x22 - Scalable
# [animations/22]
# Size=22
# Context=Animations
# Type=Scalable
# MinSize=22
# MaxSize=256

# Apps
# Odered by size

# 16x16 - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [apps/16]
# Size=16
# Context=Applications
# Type=Fixed

# 16x16@2x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [apps/16@2x]
# Size=16
# Scale=2
# Context=Applications
# Type=Fixed

# 16x16@3x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [apps/16@3x]
# Size=16
# Scale=3
# Context=Applications
# Type=Fixed

# 22x22 - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
# [apps/22]
# Size=22
# Context=Applications
# Type=Fixed

# 22x22@2x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
# [apps/22@2x]
# Size=22
# Scale=2
# Context=Applications
# Type=Fixed

# 22x22@3x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
# [apps/22@3x]
# Size=22
# Scale=3
# Context=Applications
# Type=Fixed

# 32x32 - Fixed size - For System Settings icons >!!!ONLY!!!< - Scalable to the following sizes: 32x32 (default), 64x64, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
# [apps/32]
# Size=32
# Context=Applications
# Type=Fixed

# 48x48 - Scalable - For application icons >!!!ONLY!!!< - Scalable to the following sizes: 48x48 (default), 96x96 and 24x24 (not recommended) - DO_NOT_USE_ANYWHERE_ELSE - Color
# [apps/48]
# Size=48
# Context=Applications
# Type=Scalable
# MinSize=48
# MaxSize=256

# 32x32 - Scalable - For System Settings icons >!!!ONLY!!!< - Scalable to the following sizes: 32x32 (default), 64x64, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
# [preferences/32]
# Size=32
# Context=Applications
# Type=Scalable
# MinSize=32
# MaxSize=256

# 22x22 - Fixed size - For System Settings icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Color
# [preferences/22]
# Size=22
# Context=Applications
# Type=Fixed

# 16x16 - Only used for car.svg, symlinked for KMyMoney
# [applets/16]
# Size=16
# Context=Status
# Type=Fixed

# 256x256 - Color for applets
# [applets/22]
# Size=22
# Context=Status
# Type=Scalable
# MinSize=22
# MaxSize=256

# 256x256 - Color for applets
# [applets/48]
# Size=48
# Context=Status
# Type=Scalable
# MinSize=32
# MaxSize=256

# 256x256 - Animation icons for kwin desktop effects
# [applets/64]
# Size=64
# Context=Status
# Type=Scalable
# MinSize=32
# MaxSize=256

# 256x256 - Color
# [applets/128]
# Size=128
# Context=Applications
# Type=Scalable
# MinSize=32
# MaxSize=256

# 256x256 - Scalable - For applets / widgets icons >!!!ONLY!!! - DO_NOT_USE_ANYWHERE_ELSE - Color
# [applets/256]
# Size=256
# Context=Applications
# Type=Scalable
# MinSize=48
# MaxSize=256

# Categories

# 22x22 - Category icons - Used in Plasma, MATE and Cinnamon
[categories/22]
Context=Categories
Size=22
Type=Fixed

# 32x32 - Category icons - Used in Plasma, MATE and Cinnamon
[categories/32]
Context=Categories
MaxSize=256
MinSize=32
Size=32
Type=Scalable

# Devices

# 16x16 - Fixed size - For small device icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [devices/16]
# Size=16
# Context=Devices
# Type=Fixed

# 16x16@2x - Fixed size - For small device icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [devices/16@2x]
# Size=16
# Scale=2
# Context=Devices
# Type=Fixed

# 16x16@3x - Fixed size - For small device icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [devices/16@3x]
# Size=16
# Scale=3
# Context=Devices
# Type=Fixed

# 22x22 Small Device Icons
[devices/22]
Context=Devices
Size=22
Type=Fixed

# 22x22@2x Small Device Icons
[devices/22@2x]
Context=Devices
Scale=2
Size=22
Type=Fixed

# 22x22@3x Small Device Icons
[devices/22@3x]
Context=Devices
Scale=3
Size=22
Type=Fixed

# 32x32 - Fixed size - For medium device icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [devices/32]
# Size=32
# Context=Devices
# Type=Fixed

# 32x32@2x - Fixed size - For medium device icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [devices/32@2x]
# Size=32
# Scale=2
# Context=Devices
# Type=Fixed

# 32x32@3x - Fixed size - For medium device icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [devices/32@3x]
# Size=32
# Scale=3
# Context=Devices
# Type=Fixed

# 64x64 - Scalable - For device icons >!!!ONLY!!!< - Scalable to the following sizes: 64x64 (default), 32x32, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
# [devices/64]
# Size=64
# Context=Devices
# Type=Scalable
# MinSize=24
# MaxSize=256

# Emblems

# 8x8 - File system emblems
[emblems/8]
Context=Emblems
Size=8
Type=Fixed

# 16x16 - File system emblems
[emblems/16]
Context=Emblems
Size=16
Type=Fixed

# 16x16@2x - File system emblems
[emblems/16@2x]
Context=Emblems
Scale=2
Size=16
Type=Fixed

# 16x16@3x - File system emblems
[emblems/16@3x]
Context=Emblems
Scale=3
Size=16
Type=Fixed

# 22x22 - File system emblems
[emblems/22]
Context=Emblems
Size=22
Type=Fixed

# 22x22@2x - File system emblems
[emblems/22@2x]
Context=Emblems
Scale=2
Size=22
Type=Fixed

#22x22@3x - File system emblems
[emblems/22@3x]
Context=Emblems
Scale=3
Size=22
Type=Fixed

# Emoticons
# Ordered by size

# 22x22 - Fixed size - Emoticons - DO_NOT_USE_ANYWHERE_ELSE - Color/flat
# [emotes/22]
# Size=22
# Context=Emotes
# Type=Fixed

# 22x22@2x - Fixed size - Emoticons - DO_NOT_USE_ANYWHERE_ELSE - Color/flat
# [emotes/22@2x]
# Size=22
# Scale=2
# Context=Emotes
# Type=Fixed

# 22x22@3x - Fixed size - Emoticons - DO_NOT_USE_ANYWHERE_ELSE - Color/flat
# [emotes/22@3x]
# Size=22
# Scale=3
# Context=Emotes
# Type=Fixed

# Mimetypes

# 16x16 - Small file type icons
[mimetypes/16]
Context=MimeTypes
MinSize=16
Size=16
Type=Fixed

# 16x16@2x - Small file type icons
[mimetypes/16@2x]
Context=MimeTypes
MinSize=16
Scale=2
Size=16
Type=Fixed

# 16x16@3x - Small file type icons
[mimetypes/16@3x]
Context=MimeTypes
MinSize=16
Scale=3
Size=16
Type=Fixed

# 22x22 - Small file type icons
[mimetypes/22]
Context=MimeTypes
MaxSize=24
MinSize=22
Size=22
Type=Scalable

# 22x22@2x - Small file type icons
[mimetypes/22@2x]
Context=MimeTypes
MaxSize=24
MinSize=22
Scale=2
Size=22
Type=Scalable

# 22x22@3x - Small file type icons
[mimetypes/22@3x]
Context=MimeTypes
MaxSize=24
MinSize=22
Scale=3
Size=22
Type=Scalable

# 32x32 - File type icons
[mimetypes/32]
Context=MimeTypes
Size=32
Type=Fixed

# 64x64 - File type icons
[mimetypes/64]
Context=MimeTypes
MaxSize=256
MinSize=64
Size=64
Type=Scalable

# Places

# 16x16 - Small folder icons
[places/16]
Context=Places
MinSize=16
Size=16
Type=Fixed

# 16x16@2x - Small folder icons
[places/16@2x]
Context=Places
MinSize=16
Scale=2
Size=16
Type=Fixed

# 16x16@3x - Small folder icons
[places/16@3x]
Context=Places
MinSize=16
Scale=3
Size=16
Type=Fixed

# 22x22 - Workaround icons for toolbar buttons
[places/22]
Context=Places
Size=22
Type=Fixed

# 22x22@2x - Workaround icons for toolbar buttons
[places/22@2x]
Context=Places
Scale=2
Size=22
Type=Fixed

# 22x22@3x - Workaround icons for toolbar buttons
[places/22@3x]
Context=Places
Scale=3
Size=22
Type=Fixed

# 32x32 - Folder icons
[places/32]
Context=Places
Size=32
Type=Fixed

# 48x48 - Folder icons
[places/48]
Context=Places
Size=48
Type=Fixed

# 64x64 - Folder icons
[places/64]
Context=Places
Size=64
Type=Fixed

# 96x96 - Folder icons
[places/96]
Context=Places
MaxSize=256
MinSize=96
Size=96
Type=Scalable

# Status

# 16x16 IM Status Icons
[status/16]
Context=Status
Size=16
Type=Fixed

# 16x16@2x - Fixed size - For IM status icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [status/16@2x]
# Size=16
# Scale=2
# Context=Status
# Type=Fixed

# 16x16@3x - Fixed size - For IM status icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [status/16@3x]
# Size=16
# Scale=3
# Context=Status
# Type=Fixed

# 22x22 - Icons for Theme/System Tray
[status/22]
Context=Status
Size=22
Type=Fixed

# 22x22@2x - Fixed size - Icon(s) for Plasma theme/System Tray. Not particularly used on Plasma. - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [status/22@2x]
# Size=22
# Scale=2
# Context=Status
# Type=Fixed

# 22x22@3x - Fixed size - Icon(s) for Plasma theme/System Tray. Not particularly used on Plasma. - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
# [status/22@3x]
# Size=22
# Scale=3
# Context=Status
# Type=Fixed

# 24x24 - Fixed size - for GTK apps. - WRONG_ICON_USAGE_BY_APP - Monochrome
# [status/24]
# Size=24
# Context=Status
# Type=Fixed

# 32x32 - Plasma theme/System Tray
[status/32]
Context=Status
Size=32
Type=Fixed

# 48x48 - Fixed size - For dialog icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Color
# [status/48]
# Size=48
# Context=Status
# Type=Fixed

# 64x64 - Dialog icons
[status/64]
Context=Status
MaxSize=256
MinSize=22
Size=64
Type=Scalable

# EOF